version: '3.8'
services:
  nginx:
    image: localhost:5000/tutorial-nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
  drupal:
    image: drupal:7-apache
    ports:
      - "81:80"
    volumes:
      - drupal:/var/www/html
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "root"
    ports:
      - "8080:80"
volumes:
  drupal:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/volume/tutorial/html"
  mysql:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/volume/tutorial/mysql"
