version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${PWD}/nginx:/etc/nginx/conf.d"
      - "${PWD}/nginx/certs:/certs"
  drupal:
    image: drupal:7-apache
    environment:
      DRUPAL_BASE_URL: "https://localhost"
    volumes:
      - drupal:/var/www/html
      - "${PWD}/drupal/install.php:/var/www/html/install.php"
  mysql:
    image: mysql:5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - "${PWD}/mysql/init-drupal.sql:/docker-entrypoint-initdb.d/init-drupal.sql"
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "root"
    ports:
      - "8080:80"
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
volumes:
  drupal:
  mysql:
  portainer:
