version: '3.2'
services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    deploy:
      placement:
        constraints:
          - node.role == manager
volumes:
  portainer:
